local output = arguments.output or "out"

local input
do
	if arguments.input then
		local f, err = io.open(arguments.input)
		if not f then
			print("ERROR: could not open file " .. f .. " (" .. err .. ")")
			os.exit(-1)
		end
		input = f:read("*all")
		f:close()
	else
		-- assume it was piped in
		-- NOTE: this creates the appearance of a freeze if nothing is piped in, while the shell waits for input
		input = io.read("*all")
	end
end

local undoc, parser = assert(loadstring(input))()

-- store in sorted
categorize(undoc)

local function page(title, body, depth)
	local function sidebar(depth)
		local s = ""
		for k, v in pairs(sb) do
			if v.header then
				s = s .. '<h3><a href="' .. ("../"):rep(depth) .. v.url .. '/index.html">' .. v.name .. '</a></h3>'
			else
				s = s .. '<p><a href="' .. ("../"):rep(depth) .. v.url .. '/index.html">' .. v.name .. '</a></p>'
			end
		end
		return s
	end

	if arguments.title then
		title = arguments.title .. " - " .. title
	end

	return '<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1" /><script type="text/javascript" src="' .. ("../"):rep(depth) .. 'highlight.js"></script><link rel="stylesheet" type="text/css" href="' .. ("../"):rep(depth) .. 'style.css" /><script type="text/javascript">function toggleSidebar(){var b=document.getElementById("sidebar");var a=document.getElementById("back");if(b.className==""){b.className="hide";a.style.left="5px";a.style.transform="rotate(180deg)"}else{b.className="";a.style.left="220px";a.style.transform="rotate(0deg)"}};hljs.initHighlightingOnLoad();</script><title>' .. title .. '</title></head><body><img id="back" alt="back" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAKCAQAAADWMFy7AAAAJklEQVQIHWNggIH/jFDWf7gIA5T5H4PBBFMDoeEKQFwwB8MwsAwA/nMN9+8oXa4AAAAASUVORK5CYII=" onclick="toggleSidebar()" /><div id="sidebar"><div class="container">' .. sidebar(depth) .. '</div></div><div id="content"><div class="container">' .. body .. '<div id="footer">Generated by <a href="' .. parser.url .. '">' .. parser.name .. ' ' .. parser.version .. '</a>.</div></div></body></html>'
end

fs.mkdir(output)
fs.echo(output .. "/.htaccess", "DirectoryIndex index.html")
fs.echo(output .. "/style.css", stylesheet)
fs.echo(output .. "/highlight.js", highlightjs)
for k, v in pairs(sorted) do
	local body = ""

	local function listPackages(title, trim)
		if v.has.packages then
			body = body .. "<h2>" .. title .. "</h2><table>"
			for _, pkg in pairs(v.has.packages) do
				body = body .. '<tr><td><span class="content"><a href="' .. ("../"):rep(v.depth) .. pkg.url .. '/index.html">'.. pkg.name:sub(trim) .. '</a></span><span class="description">' .. (pkg.description and pkg.description[1] or "") .. "</span>" .. "</td></tr>"
			end
			body = body .. "</table>"
		end
	end

	local function listClasses()
		if v.has.classes then
			body = body .. "<h2>Classes</h2><table>"
			for _, class in pairs(v.has.classes) do
				local super = ""
				for i = 1, #(class.superclass or {}) do
					super = super .. class.superclass[i] .. (i < #class.superclass and ", " or "")
				end
				body = body .. '<tr><td><span class="content"><a href="' .. ("../"):rep(v.depth) .. class.url .. '/index.html">' .. class.name .. '</a></span><span class="description">' .. (class.description and class.description[1] or "") .. "</span>" .. (super ~= "" and ('<div class="subclass">subclass of ' .. super .. '</div>') or "") .. "</td></tr>"
			end
			body = body .. "</table>"
		end
	end

	local function listVariables(title)
		if v.has.variables then
			body = body .. "<h2>" .. title .. "</h2><table>"
			for _, var in pairs(v.has.variables) do
				body = body .. '<tr><td class="' .. (var.scope and var.scope or "") .. '"><span class="content"><a href="' .. ("../"):rep(v.depth) .. var.url .. '/index.html">' .. var.name .. "</a>" .. (var.class and ' : <span class="class">' .. var.class .. '</span>' or "") .. (var.default and ' = <span class="default">' .. var.default .. '</span>' or "") .. '</span><span class="description">' .. (var.description and var.description[1] or "") .. "</span></td></tr>"
			end
			body = body .. "</table>"
		end
	end

	local function listFunctions(title)
		local f = 0
		if v.has.functions then
			body = body .. "<h2>" .. title .. "</h2><table>"
			for _, func in pairs(v.has.functions) do
				f = f + 1
				body = body .. '<tr class="' .. (f % 2 == 0 and "even" or "odd") .. '"><td class="' .. (func.scope and func.scope or "") .. '"><span class="content"><a href="' .. ("../"):rep(v.depth) .. func.url .. '/index.html">' .. func.name .. "("
				if func.arguments then
					for i = 1, #func.arguments do
						if type(func.arguments[i]) == "table" then
							body = body .. func.arguments[i].name .. (i < #func.arguments and ", " or "")
						else
							body = body .. func.arguments[i] .. (i < #func.arguments and ", " or "")
						end
					end
				end
				body = body .. ')</a></span><span class="description">' .. (func.description and func.description[1] or "") .. "</span></td></tr>"
				if func.arguments then
					for __, var in pairs(func.arguments) do
						if type(var) == "table" then
							body = body .. '<tr class="in small ' .. (f % 2 == 0 and "even" or "odd") .. '"><td class="' .. (var.scope and var.scope or "") .. '"><span class="content">' .. var.name .. (var.class and ' : <span class="class">' .. var.class .. '</span>' or "") .. (var.default and ' = <span class="default">' .. var.default .. '</span>' or "") .. (var.description and '</span><span class="description">' .. var.description[1] .. '</span>' or "") .. '</td></tr>'
						else
							body = body .. '<tr class="in small ' .. (f % 2 == 0 and "even" or "odd") .. '"><td><span class="content">' .. var .. "</span></td></tr>"
						end
					end
				end
				if func.returns then
					body = body .. '<tr class="in small ' .. (f % 2 == 0 and "even" or "odd") .. '"><td><span class="content"><span class="return">returns '
					for i = 1, #func.returns do
						body = body .. func.returns[i].type .. (i < #func.returns and ", " or "")
					end
					body = body .. "</span></span></td></tr>"
				end
			end
			body = body .. "</table>"
		end
	end

	local function listCode()
		if v.has.code then
			body = body .. "<h2>Example Code</h2>"
			for _, c in pairs(v.has.code) do
				body = body .. "<h4>" .. c.name .. '</h4><pre><code class="' .. c.language .. '">' .. c.code .. "</code></pre>"
			end
		end
	end

	fs.mkdir(output .. "/" .. v.path)

	body = body .. '<div class="breadcrumbs">'
	for i = 1, #(v.breadcrumbs or {}) do
		if i < #v.breadcrumbs then
			body = body .. '<a href="' .. ("../"):rep(v.depth) .. v.breadcrumbs[i].url .. 'index.html">' .. v.breadcrumbs[i].name:upper() .. '</a><span class="separator">&rsaquo;</span>'
		else
			body = body .. v.breadcrumbs[i].name:upper()
		end
	end

	body = body .. '</div><h1 class="title ' .. v.type .. (v.scope and (" " .. v.scope) or "") .. '">' .. v.name .. "</h1>"
	if v.type == "variable" then
		if v.class and v.default then
			body = body .. '<h3><span class="class">' .. v.class .. '</span> ' .. '<span class="default">(' .. v.default .. ")</span></h3>"
		elseif v.class then
			body = body .. '<h3><span class="class">' .. v.class .. "</span></h3>"
		elseif v.default then
			body = body .. '<h3><span class="default">(' .. v.default .. ')</span></h3>'
		end
	end
	if v.type == "class" and v.superclass then
		body = body .. '<h3 class="subclass">subclass of '
		for i = 1, #v.superclass do
			body = body .. v.superclass[i] .. (i < #v.superclass and ", " or "")
		end
		body = body .. '</h3>'
	end
	if v.description then
		for _, d in pairs(v.description) do
			body = body .. '<h3 class="description">' .. d .. "</h3>"
		end
	end

	if v.type == "package" or v.type == "index" then
		listPackages(v.type == "package" and "Subpackages" or "Packages", v.type == "package" and (v.name:len() + 2) or 0)
		listVariables("Variables")
		listFunctions("Functions")
		listClasses()
		listCode()
	elseif v.type == "class" then
		listVariables("Properties")
		listFunctions("Methods")
		listCode()
	elseif v.type == "function" or v.type == "constructor" then
		if v.arguments then
			body = body .. "<h2>Arguments</h2><table>"
			for _, a in pairs(v.arguments) do
				if type(a) == "table" then
					body = body .. '<tr><td class="' .. (a.scope and a.scope or "") .. '"><span class="content">' .. a.name .. (a.class and (' : <span class="class">' .. a.class) or "") .. '</span>' .. (a.default and (' = <span class="default">' .. a.default .. '</span>') or "") .. '</span><span class="description">' .. (a.description and a.description[1] or "") .. "</span></td></tr>"
				else
					body = body .. '<tr><td><span class="content">' .. a .. "</span></td></tr>"
				end
			end
			body = body .. "</table>"
		end
		if v.returns then
			body = body .. "<h2>Returns</h2><table>"
			for _, ret in pairs(v.returns) do
				if type(ret) == "table" then
					body = body .. '<tr><td><span class="content">' .. ret.type .. '</span><span class="description">' .. (ret.description or "") .. "</span></td></tr>"
				else
					body = body .. '<tr><td><span class="content">' .. ret .. "</span></td></tr>"
				end
			end
			body = body .. "</table>"
		end
		listVariables("Variables")
		listFunctions("Functions")
		listCode()
	elseif v.type == "variable" then
		listCode()
	end

	fs.echo(output .. "/" .. v.path .. "/index.html", page(v.title or v.name, body, v.depth))
end
